In [2]:
import torch

张量表示一个数值组成的数组，这个数组可能有多个维度

In [4]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

张量的shape属性访问张量的形状

In [5]:
x.shape

torch.Size([12])

张量的numel属性访问张量中元素的总数

In [6]:
x.numel()

12

改变一个张量的形状，但不改变元素的数量和元素值

In [8]:
x = x.reshape(3, 4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

使用全0，全1，其他常量或者从特定分布中随机采样的数字

In [9]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

通过提供包含数值的python列表(或嵌套列表)来为所需张量中的每个元素赋予确定值

In [11]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

常见的标准算术运算符(+,-,*,/,**)都可以升级为按元素运算

In [12]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x+y, x-y, x*y, x/y, x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

指数

In [13]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

把多个张量连在一起

In [7]:
x = torch.arange(12, dtype=torch.float32).reshape((3, 4))
y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
# dim=0在第0维合并，即在行上合并 dim=1在第1维合并，即在列上合并
torch.cat((x, y), dim=0), torch.cat((x, y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [16]:
x = torch.arange(24, dtype=torch.float32).reshape((3, 4, 2))
y = torch.ones((3, 4, 2))
print(x)
print(y)
#dim=0 3,4,2变6，4，2 dim=1 行 3,4,2变 3，8，2  dim=2 列 3,4,2变3，4，4
torch.cat((x, y), dim=0), torch.cat((x, y), dim=1), torch.cat((x, y), dim=2)#

tensor([[[ 0.,  1.],
         [ 2.,  3.],
         [ 4.,  5.],
         [ 6.,  7.]],

        [[ 8.,  9.],
         [10., 11.],
         [12., 13.],
         [14., 15.]],

        [[16., 17.],
         [18., 19.],
         [20., 21.],
         [22., 23.]]])
tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]])


(tensor([[[ 0.,  1.],
          [ 2.,  3.],
          [ 4.,  5.],
          [ 6.,  7.]],
 
         [[ 8.,  9.],
          [10., 11.],
          [12., 13.],
          [14., 15.]],
 
         [[16., 17.],
          [18., 19.],
          [20., 21.],
          [22., 23.]],
 
         [[ 1.,  1.],
          [ 1.,  1.],
          [ 1.,  1.],
          [ 1.,  1.]],
 
         [[ 1.,  1.],
          [ 1.,  1.],
          [ 1.,  1.],
          [ 1.,  1.]],
 
         [[ 1.,  1.],
          [ 1.,  1.],
          [ 1.,  1.],
          [ 1.,  1.]]]),
 tensor([[[ 0.,  1.],
          [ 2.,  3.],
          [ 4.,  5.],
          [ 6.,  7.],
          [ 1.,  1.],
          [ 1.,  1.],
          [ 1.,  1.],
          [ 1.,  1.]],
 
         [[ 8.,  9.],
          [10., 11.],
          [12., 13.],
          [14., 15.],
          [ 1.,  1.],
          [ 1.,  1.],
          [ 1.,  1.],
          [ 1.,  1.]],
 
         [[16., 17.],
          [18., 19.],
          [20., 21.],
          [22., 23.],
        

对张量中所有元素进行求和 产生只有一个元素的张量

In [17]:
x = torch.arange(12, dtype=torch.float32).reshape((3, 4))
x.sum()

tensor(66.)

即使形状不同，也可以调用广播机制（broadcasting mechanism）来执行元素操作

In [18]:
a = torch.arange(3).reshape(3, 1)
b = torch.arange(2).reshape(1, 2)
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [19]:
a + b #把a复制成3*2的矩阵(复制列) b复制成3*2的矩阵(复制行)

tensor([[0, 1],
        [1, 2],
        [2, 3]])

可以用[-1]选择最后一个元素 [1:3]选择第二个和第三个元素

In [21]:
x[-1],x[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [22]:
x[-1,-1]

tensor(11.)

In [24]:
x[1:3,2:4]

tensor([[ 6.,  7.],
        [10., 11.]])

为多个元素赋相同的值，只需要引索所有元素，然后为他们赋值

In [25]:
x[0:2,:]=12
x

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

运行一些操作可能会导致为新结果分配内存

In [27]:
y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
before = id(y)
y = y+x
id(y) == before

False

执行原地操作

In [29]:
z = torch.zeros_like(y)
print('id(z):', id(z))
z[:] = x+y
print('id(z):', id(z))

id(z): 2130864917936
id(z): 2130864917936


如果在后续操作中没有重复使用x，我们也可以使用x[:]=x+y或x+=y来减少内存的开销

In [30]:
before = id(x)
x += y
id(x) == before

True

转换为numpy张量

In [32]:
a = x.numpy()
b = torch.tensor(a)
type(a), type(b)

(numpy.ndarray, torch.Tensor)

将大小为1的张量转换为python标量

In [34]:
a=torch.tensor([3.5])
a,a.item(),float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

B相当于A的视图view 所以改B A也变了

In [3]:
import torch
a=torch.arange(12)
b=a.reshape((3,4))
b[:]=2
a

tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])