# 线性代数
标量由只有一个元素的张量表示

In [5]:
import torch

x = torch.tensor([3.0])
y = torch.tensor([2.0])

x+y, x*y, x/y, x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [4]:
k = torch.tensor(1)
k

tensor(1)

向量视为标量值组成的列表

In [6]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

通过张量的索引来访问任一元素

In [7]:
x[3]

tensor(3)

访问张量的长度

In [8]:
len(x)

4

只有一个轴的张量，形状只有一个元素

In [9]:
x.shape

torch.Size([4])

通过指定两个分量m,n来创建一个形状为m*n的矩阵

In [10]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

矩阵的转置

In [11]:
A.T  # A原值不变

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

对称矩阵 A等于其转置

In [13]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [14]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

向量是标量的推广，矩阵是向量的推广，可以构建具有更多轴的数据结构

In [22]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

给定具有相同形状的任何两个张量，任何按元素二元运算的结果都将是相同形状的张量

In [23]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B  B=A的话不分配内存 B相当于指向A的索引
A, A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

两个元素的按元素乘法称为 哈达玛积

In [24]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [28]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
X, a+X, a*X, (a*X).shape

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 tensor([[[ 0,  2,  4,  6],
          [ 8, 10, 12, 14],
          [16, 18, 20, 22]],
 
         [[24, 26, 28, 30],
          [32, 34, 36, 38],
          [40, 42, 44, 46]]]),
 torch.Size([2, 3, 4]))

计算其元素的和

In [29]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

表示任意形状张量的元素和

In [30]:
A.shape, A.sum()

(torch.Size([5, 4]), tensor(190.))

指定求和汇总张量的轴

In [32]:
A_sum_axis0 = A.sum(axis=0)  # A = torch.arange(20).reshape(5, 4)
A_sum_axis0, A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [33]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [34]:
A.sum(axis=[0, 1])  # same as A.sum()

tensor(190.)

In [35]:
k = torch.arange(24).reshape(3, 4, 2)
k

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]]])

In [36]:
k.sum(axis=0)

tensor([[24, 27],
        [30, 33],
        [36, 39],
        [42, 45]])

In [37]:
k.sum(axis=1)

tensor([[12, 16],
        [44, 48],
        [76, 80]])

In [38]:
k.sum(axis=2)

tensor([[ 1,  5,  9, 13],
        [17, 21, 25, 29],
        [33, 37, 41, 45]])

一个与求和相关的量是 平均值（mean average）

In [40]:
A.mean(), A.sum()/A.numel()

(tensor(9.5000), tensor(9.5000))

In [41]:
A.mean(axis=0), A.sum(axis=0)/A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

计算总和或均值时保持轴数不变

In [44]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

通过广播 将A除以sum_A

In [45]:
A/sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [46]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

某个轴计算A元素的累积总和

In [47]:
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

点积是相同位置的按元素乘积的和

In [48]:
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)  # dot点积

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

可以通过执行按元素乘法，进行求和 来表示两个向量的点积

In [49]:
torch.sum(x*y)

tensor(6.)

矩阵向量积Ax是一个长度为m的列向量，其i <sup>th</sup> 元素是点积$a^T_i$x

In [50]:
A.shape, x.shape, torch.mv(A, x)  # 矩阵和向量相乘 5,4 4,1---5,1

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

矩阵和矩阵的乘法AB看作是简单执行m次矩阵向量积，并将结果拼接在一起 形成n*m矩阵

In [53]:
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

$L_2$范数是向量元素平方和的平方根 $||x||_2$ = $\sqrt[2]{\sum_1^n x_i^2}$

In [54]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

$L_1$范数是向量元素的绝对值之和 $||x||_1$ = $\sum_1^n |x_i|$

In [57]:
torch.abs(u).sum()

tensor(7.)

矩阵的弗罗贝尼乌斯范数（Frobenius norm）是矩阵元素的平方和的平方根
$||X||_F$ = $\sqrt[2]{\sum_1^m\sum_1^n x_{ij}^2}$

In [67]:
torch.norm(torch.tensor([[3.0, 9.0], [4.0, 16.0]]))

tensor(19.0263)

In [74]:
a = torch.ones(2, 5, 4)
a, a.shape

(tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]),
 torch.Size([2, 5, 4]))

In [69]:
a.sum().shape #标量shape为空

torch.Size([])

In [73]:
a.sum(axis=1), a.sum(axis=1).shape

(tensor([[5., 5., 5., 5.],
         [5., 5., 5., 5.]]),
 torch.Size([2, 4]))

In [76]:
a.sum(axis=1,keepdim=True), a.sum(axis=1,keepdim=True).shape

(tensor([[[5., 5., 5., 5.]],
 
         [[5., 5., 5., 5.]]]),
 torch.Size([2, 1, 4]))

In [77]:
a.sum(axis=[0, 2])

tensor([8., 8., 8., 8., 8.])

copy可能不复制内存 clone一定复制内存 <br/>
torch中一维张量一定是行向量 列向量要用1*n矩阵来表示